# Generated by Django 4.0.3 on 2022-03-22 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='steps',
            field=models.TextField(default='1. Prepare ingredients. | 2. Cook food. | 3. Serve food.'),
        ),
    ]
