# Generated by Django 4.0.3 on 2022-04-19 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0005_mealmade'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mealmade',
            old_name='recipename',
            new_name='recipe',
        ),
        migrations.RenameField(
            model_name='mealmade',
            old_name='person_of',
            new_name='user',
        ),
    ]
