# Generated by Django 4.0.3 on 2022-04-19 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0006_rename_recipename_mealmade_recipe_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mealmade',
            name='amount',
            field=models.FloatField(),
        ),
    ]
