# Generated by Django 4.0.3 on 2022-05-02 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0008_insert_initial_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='category',
            field=models.CharField(default='', max_length=100),
        ),
    ]
