# Generated by Django 4.0.3 on 2022-05-02 13:11

from django.db import migrations

import os

def insert_initial_data(apps, schema_editor):
    for table in ['recipe', 'requirement', 'ingredient']:
        with open(os.path.join(os.path.dirname(__file__), 'default_scripts', f'insert_default_{table}.sql')) as insert_query:
            schema_editor.execute(insert_query.read())

def delete_initial_data(apps, schema_editor):
    for table in ['recipe', 'ingredient', '']:
        schema_editor.connection.execute(f"TRUNCATE recipe_{table};")


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0008_ingredient_category_alter_mealmade_user_and_more'),
    ]

    operations = [
        migrations.RunPython(code=insert_initial_data, reverse_code=delete_initial_data)
    ]
