# Generated by Django 4.0.3 on 2022-05-15 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0009_auto_20220502_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='steps',
            field=models.TextField(default='Prepare ingredients. | Cook food. | Serve food.'),
        ),
    ]
