# Generated by Django 4.0.3 on 2022-05-13 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0009_auto_20220502_2111'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpantry',
            name='amount',
        ),
    ]
