# Generated by Django 4.0.3 on 2022-05-02 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0009_alter_mealmade_user_alter_recipereview_user_and_more'),
        ('recipe', '0009_ingredient_category'),
    ]

    operations = [
    ]
