# Generated by Django 4.0.3 on 2022-05-15 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0010_alter_recipe_steps'),
        ('recipe', '0011_auto_20220513_1631'),
    ]

    operations = [
    ]
