# Generated by Django 4.0.3 on 2022-03-29 05:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dailylog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calorie_count', models.FloatField(blank=True, default=0, null=True)),
                ('quantity', models.FloatField(default=0)),
                ('total_calorie', models.PositiveIntegerField(default=0)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='mealmade',
            name='calories',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='mealmade',
            name='person_of',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Postlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calorie_amount', models.FloatField(blank=True, default=0, null=True)),
                ('amount', models.FloatField(default=0)),
                ('log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytics.dailylog')),
                ('recipename', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytics.mealmade')),
            ],
        ),
        migrations.AddField(
            model_name='dailylog',
            name='all_food_selected_today',
            field=models.ManyToManyField(related_name='inventory', through='analytics.Postlog', to='analytics.mealmade'),
        ),
        migrations.AddField(
            model_name='dailylog',
            name='food_selected',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='analytics.mealmade'),
        ),
        migrations.AddField(
            model_name='dailylog',
            name='person_of',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
