# Generated by Django 4.0.3 on 2022-03-29 06:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_dailylog_mealmade_calories_mealmade_person_of_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postlog',
            name='log',
        ),
        migrations.RemoveField(
            model_name='postlog',
            name='recipename',
        ),
        migrations.AddField(
            model_name='mealmade',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.DeleteModel(
            name='Dailylog',
        ),
        migrations.DeleteModel(
            name='Postlog',
        ),
    ]
