# Generated by Django 4.0.3 on 2022-03-29 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_remove_postlog_log_remove_postlog_recipename_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mealmade',
            name='date',
        ),
    ]
