# Generated by Django 4.0.3 on 2022-04-18 13:52

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0004_recipereview'),
        ('analytics', '0006_alter_mealmade_person_of'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mealmade',
            name='calories',
        ),
        migrations.AddField(
            model_name='mealmade',
            name='date',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='mealmade',
            name='recipename',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='recipe.recipe'),
        ),
    ]
