# Generated by Django 4.0.3 on 2022-03-09 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_address', models.EmailField(max_length=254)),
                ('username', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
                ('weight', models.DecimalField(decimal_places=2, default=60.0, max_digits=3)),
                ('height', models.DecimalField(decimal_places=2, default=160.0, max_digits=3)),
                ('weight_goal', models.DecimalField(decimal_places=2, default=60.0, max_digits=3)),
                ('calorie_goal', models.IntegerField(default=2500)),
            ],
        ),
    ]
