# Generated by Django 4.0.3 on 2022-04-30 13:30

from django.db import migrations
from decouple import config

from django.conf import settings
from django.contrib.auth.hashers import make_password

def insert_default_user(apps, schema_editor):
    # https://django-improved-user.readthedocs.io/en/stable/data_migrations.html
    User = apps.get_model(*settings.AUTH_USER_MODEL.split('.'))
    
    def_user = User.objects.create(
        email_address=config('DEFAULT_EMAIL'),
        username=config('DEFAULT_USERNAME'),
        password=make_password(config('DEFAULT_PASSWORD'))
    )
    def_user.save()

    useraccount = apps.get_model('login', 'UserAccount')

    user_account = useraccount.objects.create(user=def_user)
    user_account.user_id = def_user.id
    user_account.save()
    

class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(insert_default_user),
    ]
