# Generated by Django 4.0.3 on 2022-03-09 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_user_featured'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='featured',
        ),
    ]
