# Generated by Django 4.0.3 on 2022-05-01 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_create_default_user'),
        ('login', '0004_alter_useraccount_profile_picture'),
    ]

    operations = [
    ]
