# Generated by Django 4.0.3 on 2022-05-14 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_merge_20220501_2148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='profile_picture',
            field=models.ImageField(blank=True, null='static/pictures/default.jpg', upload_to='profile_pictures/'),
        ),
    ]
