# Generated by Django 4.0.3 on 2022-05-14 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0008_alter_useraccount_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='profile_picture',
            field=models.ImageField(blank=True, default='/media/profile_pictures/default.jpg', upload_to='profile_pictures/'),
        ),
    ]
