INSERT INTO recipe_recipe (name, tags)
VALUES
	('Pepperoni Pizza', 'Pizza Bake Dough Oil Tomato Salty Pepperoni Cheese Snack Lunch Fancy Party'),
	('Omelette', 'Egg Salty Breakfast Omelette'),
	('Bacon', 'Pork Fried Oil Fats Breakfast Salty Bacon'),
	('Ceasar Salad', 'Vegetables Greens Healthy Lettuce Savory Carrots Salad'),
	('Beef Tapa', 'Beef Fats Oils Savory Salty Filipino Tapa Breakfast'),
	('Pancake', 'Breakfast Sweet Pastry Egg Pancake'),
	('Steak', 'Beef Steak Fancy Date Savory Dinner'),
	('Mushroom Soup', 'Soup Mushroom Savory Lunch Breakfast Dinner'),
	('Fried Rice', 'Rice Fried Shrimp Butter Savory Lunch Breakfast Dinner'),
	('Spaghetti', 'Noodles Spaghetti Savory Cheese Tomato Snack Lunch Breakfast Dinner'),
	('Fried Chicken', 'Chicken Fried Oil Salty Lunch Fancy Party'),
	('Mango Shake', 'Mango Healthy Cold Milk'),
	('Baked Macaroni', 'Tomato Macaroni Savory Cheese Tomato Snack Lunch'),
	('Cheesecake', 'Cheesecake Sweet Cake Snack Dessert'),
	('Chicken Nuggets', 'Chicken Nuggets Salty Oil Fried Bite-sized Party'),
	('Yogurt', 'Yogurt Salty Healthy Dessert Breakfast Lunch Dinner'),
	('Yang Chow Rice', 'Yang-Chow Rice Butter Fried Beef Vegetables Chinese'),
	('Lumpiang Shanghai', 'Lumpia Shanghai Oil Fried Party Salty'),
	('Tonkatsu', 'Tonkatsu Japanese Pork Cutlet Savory Fried'),
	('Four-Cheese Pizza', 'Pizza Bake Dough Oil Tomato Salty Mozarella Cheese Snack Lunch Fancy Party')