# Generated by Django 4.0.3 on 2022-03-13 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pantry', '0002_alter_ingredients_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredients',
            name='img',
            field=models.ImageField(upload_to='media/'),
        ),
    ]
