# Generated by Django 4.0.3 on 2022-03-25 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pantry', '0003_alter_ingredients_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredients',
            name='img',
            field=models.ImageField(upload_to=''),
        ),
    ]
