# Generated by Django 4.0.3 on 2022-04-19 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pantry', '0004_alter_ingredients_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredients',
            name='img',
        ),
    ]
